version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PG_DB_DSN: postgres://postgres:password@db:5432/  
    depends_on:
      - db  

  db:
    image: postgres:latest
    container_name: postgres-ptzen
    environment:
      POSTGRES_DB: assesment_ptzen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 
